#!/bin/bash
#
# Test ASI 120 MM with INDI command line tools
#
# Originally from:
# https://indilib.org/forum/ccds-dslrs/1730-asi-120mc-bug.html?start=12#12977
#

# Result of indi_getprop when connected:
# ZWO CCD ASI120MM.CONNECTION.CONNECT=On
# ZWO CCD ASI120MM.CONNECTION.DISCONNECT=Off
# ZWO CCD ASI120MM.DRIVER_INFO.DRIVER_NAME=ZWO CCD
# ZWO CCD ASI120MM.DRIVER_INFO.DRIVER_EXEC=indi_asi_ccd
# ZWO CCD ASI120MM.DRIVER_INFO.DRIVER_VERSION=2.7
# ZWO CCD ASI120MM.DRIVER_INFO.DRIVER_INTERFACE=6
# ZWO CCD ASI120MM.POLLING_PERIOD.PERIOD_MS=1000
# ZWO CCD ASI120MM.DEBUG.ENABLE=Off
# ZWO CCD ASI120MM.DEBUG.DISABLE=On
# ZWO CCD ASI120MM.SIMULATION.ENABLE=Off
# ZWO CCD ASI120MM.SIMULATION.DISABLE=On
# ZWO CCD ASI120MM.CONFIG_PROCESS.CONFIG_LOAD=Off
# ZWO CCD ASI120MM.CONFIG_PROCESS.CONFIG_SAVE=Off
# ZWO CCD ASI120MM.CONFIG_PROCESS.CONFIG_DEFAULT=Off
# ZWO CCD ASI120MM.CONFIG_PROCESS.CONFIG_PURGE=Off
# ZWO CCD ASI120MM.ACTIVE_DEVICES.ACTIVE_TELESCOPE=Telescope Simulator
# ZWO CCD ASI120MM.ACTIVE_DEVICES.ACTIVE_ROTATOR=Rotator Simulator
# ZWO CCD ASI120MM.ACTIVE_DEVICES.ACTIVE_FOCUSER=Focuser Simulator
# ZWO CCD ASI120MM.ACTIVE_DEVICES.ACTIVE_FILTER=CCD Simulator
# ZWO CCD ASI120MM.ACTIVE_DEVICES.ACTIVE_SKYQUALITY=SQM
# ZWO CCD ASI120MM.CCD_EXPOSURE.CCD_EXPOSURE_VALUE=0.10000000149011611938
# ZWO CCD ASI120MM.CCD_ABORT_EXPOSURE.ABORT=Off
# ZWO CCD ASI120MM.CCD_FRAME.X=0
# ZWO CCD ASI120MM.CCD_FRAME.Y=0
# ZWO CCD ASI120MM.CCD_FRAME.WIDTH=1280
# ZWO CCD ASI120MM.CCD_FRAME.HEIGHT=960
# ZWO CCD ASI120MM.CCD_BINNING.HOR_BIN=1
# ZWO CCD ASI120MM.CCD_BINNING.VER_BIN=1
# ZWO CCD ASI120MM.CCD_CAPTURE_FORMAT.ASI_IMG_RAW8=Off
# ZWO CCD ASI120MM.CCD_CAPTURE_FORMAT.ASI_IMG_RAW16=On
# ZWO CCD ASI120MM.CCD_TRANSFER_FORMAT.FORMAT_FITS=On
# ZWO CCD ASI120MM.CCD_TRANSFER_FORMAT.FORMAT_NATIVE=Off
# ZWO CCD ASI120MM.CCD_TRANSFER_FORMAT.FORMAT_XISF=Off
# ZWO CCD ASI120MM.CCD_INFO.CCD_MAX_X=1280
# ZWO CCD ASI120MM.CCD_INFO.CCD_MAX_Y=960
# ZWO CCD ASI120MM.CCD_INFO.CCD_PIXEL_SIZE=3.75
# ZWO CCD ASI120MM.CCD_INFO.CCD_PIXEL_SIZE_X=3.75
# ZWO CCD ASI120MM.CCD_INFO.CCD_PIXEL_SIZE_Y=3.75
# ZWO CCD ASI120MM.CCD_INFO.CCD_BITSPERPIXEL=16
# ZWO CCD ASI120MM.CCD_COMPRESSION.INDI_ENABLED=Off
# ZWO CCD ASI120MM.CCD_COMPRESSION.INDI_DISABLED=On
# ZWO CCD ASI120MM.TELESCOPE_TIMED_GUIDE_NS.TIMED_GUIDE_N=0
# ZWO CCD ASI120MM.TELESCOPE_TIMED_GUIDE_NS.TIMED_GUIDE_S=0
# ZWO CCD ASI120MM.TELESCOPE_TIMED_GUIDE_WE.TIMED_GUIDE_W=0
# ZWO CCD ASI120MM.TELESCOPE_TIMED_GUIDE_WE.TIMED_GUIDE_E=0
# ZWO CCD ASI120MM.CCD_FRAME_TYPE.FRAME_LIGHT=On
# ZWO CCD ASI120MM.CCD_FRAME_TYPE.FRAME_BIAS=Off
# ZWO CCD ASI120MM.CCD_FRAME_TYPE.FRAME_DARK=Off
# ZWO CCD ASI120MM.CCD_FRAME_TYPE.FRAME_FLAT=Off
# ZWO CCD ASI120MM.SCOPE_INFO.FOCAL_LENGTH=0
# ZWO CCD ASI120MM.SCOPE_INFO.APERTURE=0
# ZWO CCD ASI120MM.WCS_CONTROL.WCS_ENABLE=Off
# ZWO CCD ASI120MM.WCS_CONTROL.WCS_DISABLE=On
# ZWO CCD ASI120MM.UPLOAD_MODE.UPLOAD_CLIENT=Off
# ZWO CCD ASI120MM.UPLOAD_MODE.UPLOAD_LOCAL=On
# ZWO CCD ASI120MM.UPLOAD_MODE.UPLOAD_BOTH=Off
# ZWO CCD ASI120MM.UPLOAD_SETTINGS.UPLOAD_DIR=/home/mj
# ZWO CCD ASI120MM.UPLOAD_SETTINGS.UPLOAD_PREFIX=IMAGE_XXX
# ZWO CCD ASI120MM.CCD_FAST_TOGGLE.INDI_ENABLED=Off
# ZWO CCD ASI120MM.CCD_FAST_TOGGLE.INDI_DISABLED=On
# ZWO CCD ASI120MM.CCD_FAST_COUNT.FRAMES=1
# ZWO CCD ASI120MM.CCD_VIDEO_STREAM.STREAM_ON=Off
# ZWO CCD ASI120MM.CCD_VIDEO_STREAM.STREAM_OFF=On
# ZWO CCD ASI120MM.STREAM_FULL_DEPTH.FULL_DEPTH_8BIT=On
# ZWO CCD ASI120MM.STREAM_FULL_DEPTH.FULL_DEPTH_16BIT=Off
# ZWO CCD ASI120MM.STREAM_DELAY.STREAM_DELAY_TIME=0
# ZWO CCD ASI120MM.STREAMING_EXPOSURE.STREAMING_EXPOSURE_VALUE=0.10000000000000000555
# ZWO CCD ASI120MM.STREAMING_EXPOSURE.STREAMING_DIVISOR_VALUE=1
# ZWO CCD ASI120MM.FPS.EST_FPS=30
# ZWO CCD ASI120MM.FPS.AVG_FPS=30
# ZWO CCD ASI120MM.RECORD_STREAM.RECORD_ON=Off
# ZWO CCD ASI120MM.RECORD_STREAM.RECORD_DURATION_ON=Off
# ZWO CCD ASI120MM.RECORD_STREAM.RECORD_FRAME_ON=Off
# ZWO CCD ASI120MM.RECORD_STREAM.RECORD_OFF=On
# ZWO CCD ASI120MM.RECORD_FILE.RECORD_FILE_DIR=/home/mj/Videos/indi__D_
# ZWO CCD ASI120MM.RECORD_FILE.RECORD_FILE_NAME=indi_record__T_
# ZWO CCD ASI120MM.RECORD_OPTIONS.RECORD_DURATION=1
# ZWO CCD ASI120MM.RECORD_OPTIONS.RECORD_FRAME_TOTAL=30
# ZWO CCD ASI120MM.CCD_STREAM_FRAME.X=0
# ZWO CCD ASI120MM.CCD_STREAM_FRAME.Y=0
# ZWO CCD ASI120MM.CCD_STREAM_FRAME.WIDTH=1280
# ZWO CCD ASI120MM.CCD_STREAM_FRAME.HEIGHT=960
# ZWO CCD ASI120MM.CCD_STREAM_ENCODER.RAW=On
# ZWO CCD ASI120MM.CCD_STREAM_ENCODER.MJPEG=Off
# ZWO CCD ASI120MM.CCD_STREAM_RECORDER.SER=On
# ZWO CCD ASI120MM.LIMITS.LIMITS_BUFFER_MAX=512
# ZWO CCD ASI120MM.LIMITS.LIMITS_PREVIEW_FPS=10
# ZWO CCD ASI120MM.CCD_TEMPERATURE.CCD_TEMPERATURE_VALUE=23
# ZWO CCD ASI120MM.CCD_CONTROLS.Gain=75
# ZWO CCD ASI120MM.CCD_CONTROLS.Offset=0
# ZWO CCD ASI120MM.CCD_CONTROLS.BandWidth=40
# ZWO CCD ASI120MM.CCD_CONTROLS.AutoExpMaxGain=50
# ZWO CCD ASI120MM.CCD_CONTROLS.AutoExpMaxExpMS=30000
# ZWO CCD ASI120MM.CCD_CONTROLS.AutoExpTargetBrightness=100
# ZWO CCD ASI120MM.CCD_CONTROLS.HighSpeedMode=0
# ZWO CCD ASI120MM.CCD_CONTROLS_MODE.AUTO_Gain=Off
# ZWO CCD ASI120MM.CCD_CONTROLS_MODE.AUTO_BandWidth=Off
# ZWO CCD ASI120MM.FLIP.FLIP_HORIZONTAL=Off
# ZWO CCD ASI120MM.FLIP.FLIP_VERTICAL=Off
# ZWO CCD ASI120MM.CCD_VIDEO_FORMAT.ASI_IMG_RAW8=Off
# ZWO CCD ASI120MM.CCD_VIDEO_FORMAT.ASI_IMG_RAW16=On
# ZWO CCD ASI120MM.BLINK.BLINK_COUNT=0
# ZWO CCD ASI120MM.BLINK.BLINK_DURATION=0
# ZWO CCD ASI120MM.ADC_DEPTH.BITS=12
# ZWO CCD ASI120MM.SDK.VERSION=1, 41, 0, 0
# ZWO CCD ASI120MM.USB_RESET.INDI_ENABLED=Off
# ZWO CCD ASI120MM.USB_RESET.INDI_DISABLED=On
# ZWO CCD ASI120MM.CCD_FILE_PATH.FILE_PATH=
# ZWO CCD ASI120MM.ACTIVE_DEVICES.ACTIVE_TELESCOPE=Telescope Simulator
# ZWO CCD ASI120MM.ACTIVE_DEVICES.ACTIVE_ROTATOR=Rotator Simulator
# ZWO CCD ASI120MM.ACTIVE_DEVICES.ACTIVE_FOCUSER=Focuser Simulator
# ZWO CCD ASI120MM.ACTIVE_DEVICES.ACTIVE_FILTER=CCD Simulator
# ZWO CCD ASI120MM.ACTIVE_DEVICES.ACTIVE_SKYQUALITY=SQM
# ZWO CCD ASI120MM.CCD_VIDEO_STREAM.STREAM_ON=Off
# ZWO CCD ASI120MM.CCD_VIDEO_STREAM.STREAM_OFF=On
# ZWO CCD ASI120MM.STREAM_FULL_DEPTH.FULL_DEPTH_8BIT=On
# ZWO CCD ASI120MM.STREAM_FULL_DEPTH.FULL_DEPTH_16BIT=Off
# ZWO CCD ASI120MM.STREAMING_EXPOSURE.STREAMING_EXPOSURE_VALUE=0.10000000000000000555
# ZWO CCD ASI120MM.STREAMING_EXPOSURE.STREAMING_DIVISOR_VALUE=1
# ZWO CCD ASI120MM.FPS.EST_FPS=30
# ZWO CCD ASI120MM.FPS.AVG_FPS=30
# ZWO CCD ASI120MM.RECORD_STREAM.RECORD_ON=Off
# ZWO CCD ASI120MM.RECORD_STREAM.RECORD_DURATION_ON=Off
# ZWO CCD ASI120MM.RECORD_STREAM.RECORD_FRAME_ON=Off
# ZWO CCD ASI120MM.RECORD_STREAM.RECORD_OFF=On
# ZWO CCD ASI120MM.RECORD_FILE.RECORD_FILE_DIR=/home/mj/Videos/indi__D_
# ZWO CCD ASI120MM.RECORD_FILE.RECORD_FILE_NAME=indi_record__T_
# ZWO CCD ASI120MM.RECORD_OPTIONS.RECORD_DURATION=1
# ZWO CCD ASI120MM.RECORD_OPTIONS.RECORD_FRAME_TOTAL=30
# ZWO CCD ASI120MM.CCD_STREAM_FRAME.X=0
# ZWO CCD ASI120MM.CCD_STREAM_FRAME.Y=0
# ZWO CCD ASI120MM.CCD_STREAM_FRAME.WIDTH=1280
# ZWO CCD ASI120MM.CCD_STREAM_FRAME.HEIGHT=960
# ZWO CCD ASI120MM.CCD_STREAM_ENCODER.RAW=On
# ZWO CCD ASI120MM.CCD_STREAM_ENCODER.MJPEG=Off
# ZWO CCD ASI120MM.CCD_STREAM_RECORDER.SER=On
# ZWO CCD ASI120MM.LIMITS.LIMITS_BUFFER_MAX=512
# ZWO CCD ASI120MM.LIMITS.LIMITS_PREVIEW_FPS=10


indi_setprop "ZWO CCD ASI120MM.CONNECTION.CONNECT=On"
indi_setprop "ZWO CCD ASI120MM.CCD_CONTROLS_MODE.AUTO_Gain=Off"
indi_setprop "ZWO CCD ASI120MM.CCD_CONTROLS.Gain=75"

indi_setprop "ZWO CCD ASI120MM.UPLOAD_MODE.UPLOAD_LOCAL=On"
# indi_setprop "ZWO CCD ASI120MM.CCD_COMPRESSION.CCD_RAW=Off"
# indi_setprop "ZWO CCD ASI120MM.CCD_COMPRESSION.CCD_COMPRESS=On"
indi_setprop "ZWO CCD ASI120MM.CCD_CAPTURE_FORMAT.ASI_IMG_RAW8=On"

exp=5
echo "exposure: $exp"

indi_setprop "ZWO CCD ASI120MM.CCD_EXPOSURE.CCD_EXPOSURE_VALUE=$exp"
sleep 1

for i in $(seq 1 1000); do
    if [ "$(indi_getprop 'ZWO CCD ASI120MM.CCD_EXPOSURE.CCD_EXPOSURE_VALUE' 2>/dev/null | cut -d '=' -f 2)" == "0" ]; then
        break
    fi
    sleep 1
done
